apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudcart-config
  namespace: cloudcart
data:
  APP_NAME: "CloudCart API"
  ENVIRONMENT: "kubernetes-local"
  DB_HOST: "cloudcart-postgres"
  DB_PORT: "5432"
  DB_NAME: "cloudcart"