apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cloudcart
  labels:
    app: cloudcart-backend
    purpose: frontend-nginx-proxy-alias
spec:
  type: ClusterIP
  selector:
    app: cloudcart-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000